@echo off
cd /d "%~dp0"
echo Limpando cache do npm...
call npm cache clean --force
echo Removendo node_modules...
rmdir /s /q node_modules 2>nul
echo Removendo package-lock.json...
del /f /q package-lock.json 2>nul
echo.
echo Configurando npm para Windows...
call npm config set platform win32
call npm config set arch x64
echo.
echo Instalando dependencias...
call npm install
echo.
echo Instalando pacote Rollup para Windows...
call npm install --force @rollup/rollup-win32-x64-msvc
echo.
echo Verificando instalacao do Rollup...
dir node_modules\@rollup\
echo.
echo Iniciando servidor de desenvolvimento...
call npm run dev
